elasticsearch:
  nodes: 127.0.0.1:9200,127.0.0.1:9201
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: admin123
    type: com.alibaba.druid.pool.DruidDataSource